### ISSUE TITLE
Bitcoin original version works well or not ?

### ISSUE THREAD

**Issue by meilier** [Dan-McG/bitcoin-0.1.0#1]
I run bitcoin.exe on two windows computers. It shows it is Generating and 1connetions, 1blocks,0 transations.And I search google my cpu hashrate, it cost about 42 hours to generate one block. so, I just wait for two days, and one of the bitcoin client can get initial coins? Thanks

**Comment by Dan-McG** [comment]
> Bitcoin original version works well or not ?

Not.

But well done compiling it!

**Comment by meilier** [comment]
yes，I compile bitcoin v0.1.0 source code。Preparing to release a altcoin for testing.May it works!
